name: Scheduler

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - uses: dschep/install-pipenv-action@v1
      with:
        version: 2020.8.13
    - name: Install dependencies
      run: |
        pipenv sync
    - uses: dawidd6/action-download-artifact@v2
      with:
        name: result_json
        workflow: schedule.yml
    - name: Main
      if: success() || failure()
      run: |
        pipenv run start "${ARG}"
      env:
        ARG: .products.json
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: result_json
        path: .products.json
